# app.py
from flask import Flask
import subprocess
import os
from datetime import datetime
import pytz

app = Flask(__name__)

@app.route('/htop')
def htop():
    name = "Your Full Name"
    username = os.getlogin()
    
    ist_time = datetime.now(pytz.timezone('Asia/Kolkata'))
    
    top_output = subprocess.getoutput("top -b -n 1")

    html = f"""
    <h3>Name: {name}</h3>
    <h3>User: {username}</h3>
    <h3>Server Time (IST): {ist_time}</h3>
    <pre>{top_output}</pre>
    """
    return html

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
